name: Angular & Cypress Tests

on: [push, pull_request]

jobs:
  angular-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test -- --watch=false --browsers=ChromeHeadless

  cypress-tests:
    runs-on: ubuntu-latest
    needs: angular-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: |
          npm run start &
          npx wait-on http://localhost:4200
      - uses: cypress-io/github-action@v5
        with:
          start: npm run start
